fix: 修复并发模式下缓存会失效的 bug
ecomfe/react-suspense-boundary pull request #30
Opened 2023-10-26 15:41 UTC by maaye3210

如果请求被响应的太快,就会在 CacheProvider 这个组件被 mount 之前就将 promise 解决，从而触发 Suspense 的渲染流程；而 CacheProvider 这个组件还没有被 mount，就会重新生成 Fiber，Context 也会被重置。最终造成重复渲染。
使用 useLayout 和 另一个 Promise 将 Suspense 的渲染流程延迟到 CacheProvider 这个组件被 mount 之后

2024-03-20 04:33 UTC, Sharonzd commented
补充一些关于问题复现的额外信息：
UserList 组件里有两个请求，如果只监测 api.list 请求被调用了多少次是难以发现问题，因为前面还有一个请求是 noCrash。修复之前 noCrash 被重复调用了 2000 多次（如前面的问题分析，请求 resolve 越快，重复渲染次数越多），等轮得到 api.list 时组件 ready 了所以看起来 api.list 只执行了一次。但是如果把 noCrash 这个请求去掉，那么重复执行的就是 api.list 了。

<img width="1746" alt="image" src="https://github.com/ecomfe/react-suspense-boundary/assets/12129112/3bd09596-0756-4013-adc9-b78382790edc">

修复之后 noCrash 请仅执行一次。
<img width="1895" alt="image" src="https://github.com/ecomfe/react-suspense-boundary/assets/12129112/020615e4-112c-4996-a281-c0d54a30062e">

2024-03-21 06:11 UTC, otakustay requested changes

2024-03-21 06:11 UTC, otakustay commented on src/cache.tsx
> +    let promiseResolver = null as unknown as () => void;
这里取`resolve`的逻辑，实际上对应新的JS中的`Promise.withResolvers`方法，我建议单独声明一个`promiseWithResolvers`函数出来，签名保持和`Promise.withResolvers`一致，以便于后面兼容性OK了可以快速替换

2024-03-21 06:11 UTC, otakustay commented on src/cache.tsx
> +            throw promise.then(() => promiseReturn);
这个逻辑是不是`Promise.all([promise, promiseReturn])`？

2024-03-21 06:11 UTC, otakustay commented on src/cache.tsx
> +        const {cache, promise: promiseReturn} = useContext(Context);
`promiseReturn`这个命名几乎完全看不懂啥意思，是不是弄个`promisePendingComponentMount`之类的

2024-03-21 12:27 UTC, Sharonzd commented on src/cache.tsx
> +            throw promise.then(() => promiseReturn);
这里用 promise.all 可以提高渲染性能，避免串行等待。

throw Promise.all([promise, promiseReturn]);

2024-03-21 12:27 UTC, Sharonzd commented on src/cache.tsx
> +    promise: Promise<void>;
建议命名更加语义化一点

compMountResolver
compMountPromise

2024-03-21 12:27 UTC, Sharonzd commented on demo/components/App/index.tsx
> +        {/* <SuspenseError /> */}
demo 不要影响整体页面。应该在下面最后加一个路由页面

如
  <Route path="/cache-provider" element={<Cache />} />

2024-03-21 12:27 UTC, Sharonzd commented on demo/components/SuspenseError/index.tsx
> +export default SuspenseError;
SuspenseError 这个组件命名语义有点困惑，可以就叫 Cache
内层组件 FetchComponents 语义也不明确，可以叫 LazyComponent

2024-03-21 12:27 UTC, Sharonzd commented on demo/components/SuspenseError/components/FetchComponent.tsx
> +                    <Component />
demo 的内容组件应该和其他 demo 一致，统一使用 UserList 组件，以保证页面的完整性。

可以修改 UserList 以复现问题和修复的效果。要改的很少，把 nocrash 函数改成以下就行了
```
const noCrash = () => {
    console.log('resource 请求被执行了');
    return new Promise(
        resolve => setTimeout(resolve, 0)
    );
}; 
```

2024-03-21 12:27 UTC, Sharonzd commented on package.json
> +    "react": "^18.2.0",
升级 @types 到 18 可以理解，但其他的依赖库最好不要动。

2024-03-21 12:27 UTC, Sharonzd commented on src/cache.tsx
> +    let promiseResolver = null as unknown as () => void;
不要用 as 来断言类型，直接声明正确的类型

```
let compMountResolver:  (value?: (PromiseLike<void> | void)) => void = () => {};
const compMountPromise = new Promise<void>(resolve => {
    compMountResolver = resolve;
});

return {
    cache,
    compMountResolver,
    compMountPromise,
};
```

2024-03-21 12:28 UTC, Sharonzd commented
诶，我的评论没发出去 …

2024-03-21 12:37 UTC, otakustay commented on src/cache.tsx
> +    return {cache, promiseResolver: resolve, promisePendingComponentMount: promise, num: Math.random()};
这个`num`是什么？我没看到有其它使用的地方？

2024-03-21 12:37 UTC, otakustay commented on package.json
> +    "react": "^18.2.0",
这块是`devDependencies`，问题不大～

2024-03-21 12:48 UTC, maaye3210 commented on src/cache.tsx
> +    return {cache, promiseResolver: resolve, promisePendingComponentMount: promise, num: Math.random()};
调试用的，没有删干净

2024-03-21 13:07 UTC, maaye3210 commented on src/cache.tsx
> +    let promiseResolver = null as unknown as () => void;
现在已经改写成了 Promise.withResolvers 的格式

2024-03-21 13:48 UTC, Sharonzd commented on src/cache.tsx
> +        resolve = resolver;
你这里的 ts 不会报错吗。还有下面也不需要用 as const

完整的类型应该是  (value?: (PromiseLike<void> | void)) => void

2024-03-21 13:49 UTC, Sharonzd commented on src/cache.tsx
> +        resolve = resolver;
完整的类型应该是： (value?: (PromiseLike<void> | void)) => void

2024-03-22 03:33 UTC, otakustay approved these changes

2024-03-22 03:33 UTC, merged